version: '3.8'

services:
  db:
    image: postgres:14
    container_name: beetle_db
    profiles:
      - db
      - all
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-beetle}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./assets/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: beetle_adminer
    profiles:
      - db
      - all
    ports:
      - "18080:8080"
    depends_on:
      - db

volumes:
  postgres_data: 